### ISSUE TITLE
 Numerical error in gradient : Tensor had NaN values

### ISSUE THREAD

**Issue by zjhthu** [vcg-uvic/learned-correspondence-release#1]
I train the model from scratch but soon encounter the NaN problem several times: `2018-06-22 23:30:42.664766: E tensorflow/core/kernels/check_numerics_op.cc:185] abnormal_detected_host @0x2049e8d00 = {1, 0} Numerical error in gradient for Matchnet
/hidden-input/self-conv/weights:0`

So do you have any suggestions?

**Comment by kmyid** [comment]
That's interesting. If you look at the code, you'll see that there's a try-catch to skip training batches that cause numerical errors. Thus, the training should probably give that message but would not have any problems in the training process. Does the code crash?

**Comment by zjhthu** [comment]
yes, it crashed.

**Comment by kmyid** [comment]
That's weird. Can you detail more on the run command, your TF version, OS, which dataset and setup?

Cheers,
Kwang

**Comment by zjhthu** [comment]
Ubuntu 16.04, python2.7, tensorflow 1.7 as in the `requirements.txt`,  cuda-9.0, cudnn-7.0.
I prepare dataset as in the readme: `python dump_data.py --data_tr=st_peters --data_va=st_peters --data_te=st_peters`. In order to run the script, I directly set `data_dir = "./datasets/"` in config.py and comment these lines,
```    # Setup the base directory depending on the environment
    if is_computecanada():
        data_dir = "/scratch/kyi/datasets/scenedata_splits/"
    elif is_vcg_uvic():
        data_dir = "/data/datasets/sfm/scenedata_splits/"
    elif is_cvlab_epfl():
        data_dir = "/cvlabdata2/home/kyi/Datasets/scenedata_splits/"
    else:
        data_dir = "./datasets/"
```
because it will crash in `is_computecanada()`, `AttributeError: 'NoneType' object has no attribute 'startswith'`.
The training command is `python main.py --run_mode=train`

**Comment by kmyid** [comment]
I'm still at CVPR. @xyukiono can you test this if you have the time? If not, I'll try when I get back in two weeks.

**Comment by kmyid** [comment]
Can you also post the entire error message?

**Comment by kmyid** [comment]
Wild guess, try Python3, I think Python 2 might not have the valueerror catch.

**Comment by zjhthu** [comment]
Python3 does not work either.

**Comment by zjhthu** [comment]
the log file is attached.
[log.txt](https://github.com/vcg-uvic/learned-correspondence-release/files/2129803/log.txt)

**Comment by kmyid** [comment]
Ah, it’s because the Error type somehow changed. Change ValueError to the error type in the log and that should solve it.

Message written with iPhone. 
Please excuse any brievity and typos.
_________  

Kwang Moo YI
Assistant Professor
Department of Computer Science
University of Victoria
+1 (250) 475 5837

2018. 6. 23. 03:39, zhang <notifications@github.com> 작성:

**Comment by zjhthu** [comment]
Thanks! It works.
