### ISSUE TITLE
data preprocessing step

### ISSUE THREAD

**Issue by hua-wu-que** [vcg-uvic/learned-correspondence-release#10]
specifically, in line 227-229 of dump_data.py: why the reprojection are calculated by setting the depth to 1?

**Comment by kmyid** [comment]
For 

https://github.com/vcg-uvic/learned-correspondence-release/blob/82adffad3f6fa3ea52aba9919cef00955c6d1617/dump_data.py#L227

we are placing them on the calibrated image plane. For more details, please see Hartley and Zisserman's book.
