### ISSUE TITLE
from gms_matcher import GmsMatcher

### ISSUE THREAD

**Issue by TracesChen** [vcg-uvic/learned-correspondence-release#22]
hello
        Be grateful for sharing code ，I want to implement you code :" config. Run_Mode = = "comp" "，But I can‘t find gms_matcher.py package .There is a big difference between it and GMS，Can you share it with me？ Thank you very much ！

**Comment by kmyid** [comment]
Hello, 

That part of the code is adapted from the gms method's original code base. I am not sure I can share that part immediately. However, the only thing I do, if I recall correctly, is to use options either to allow rotations and scaling or not.

**Comment by TracesChen** [comment]
Thank you for your reply! I will use GMS model
