### ISSUE TITLE
dataset calibration

### ISSUE THREAD

**Issue by yishiliuhuasheng** [vcg-uvic/learned-correspondence-release#3]
I want to know something about the calibration h5 file of dataset. Can you provide some information about the parameters in this calibration file?

**Comment by weiweisun2018** [comment]
As I understand, it should be the [Detail of decoding calibration h5 file](https://github.com/vcg-uvic/learned-correspondence-release/blob/9e401f2752c4396cea9c0a723b819b894cf96f10/data.py#L48).  The parameters should include K (i.e., cx, cy, fx, fy), R, t. Hope it might be helpful.

**Comment by yishiliuhuasheng** [comment]
Thank you very much for your replay. That would be very helpful to me!
