### ISSUE TITLE
What is the 'dc' value in the calibration_000001.h5 file?

### ISSUE THREAD

**Issue by punisher220** [vcg-uvic/learned-correspondence-release#36]
Excuse me, I read the data from the calibration_00000x.h5 file and there are 5 keys in total: **K , R, T, dc and imsize**
  I am sure that the K is for Intrinsic parameters, R is for Extrinsic parameters as rotation part, T is for Extrinsic parameters as transform part and imsize is the size of the referred image.

  What is the **'dc'** value? It is a float number and the range is (-1,1). What does it mean for the camera parameters?

**Comment by etrulls** [comment]
It's an unused parameter copied over from VisualSFM (a distortion coefficient, I imagine?); you can just ignore it.

**Comment by punisher220** [comment]
Thanks for your reply
