### ISSUE TITLE
cv2.BFmatcher before run_model() call in single image pair test?

### ISSUE THREAD

**Issue by ZeroSteven618** [vcg-uvic/learned-correspondence-release#38]
Excuse me, thanks to @ignacio-rocco, the demo for testing on image pair is available.
  However, I have a question, in the image pair test demo, the keypoints are extracted from SIFT and then cv2.BFMatcher was used before the network loading. It seems that the network is an optimization based on an existing match result. Is it right?
  I read the **main.py --run_mode=test ...** part code and I also found that in **test_process()** call you used  SIFT matching then network processing to get a better matching. But I am not sure about it.

  So the main question I would like to confirm is:   
  Can the repo do keypoint matching without any pre-matching such as SIFT or any other tools?
  For example, if I got 
 
`cv_kp_1, cv_desc_1 = sift.detectAndCompute(im_1, None)` 
`cv_kp_2, cv_desc_2 = sift.detectAndCompute(im_2, None)`

  Then can I use the repo work to get matching based on the **cv_kp_1, cv_desc_1** and **cv_kp_2, cv_desc_2** above without the help of cv2.matching tools for pre-matching?

**Comment by etrulls** [comment]
This method "replaces" geometric outlier rejection, not the initial matching. If you extract, say, 1k features per image without any type of filtering you get 1M potential matches, most of which are incorrect (at least 99.9%, by definition). Nearly all works on this topic, learned of hand-crafted, constrain this to e.g. nearest neighbours only (sometimes enforcing bidirectionality as well). You could use all matches as input, but you would increase memory/compute and get worse results.

**Comment by ZeroSteven618** [comment]
Thanks for your immediate reply!
**This method "replaces" geometric outlier rejection, not the initial matching.** 
Well, I confirmed that the repo is like RANSAC for outlier rejection rather than initial matching.
But the repo can work together with RANSAC.
Thanks.
