### ISSUE TITLE
How to get the matching pair evaluation visualization?

### ISSUE THREAD

**Issue by ZeroSteven618** [vcg-uvic/learned-correspondence-release#39]
Excuse me, I wonder the process of the matching pairs lining with green and red for evaluation display as follows:
![inquiry](https://user-images.githubusercontent.com/66064813/97837078-843ddf00-1d18-11eb-9344-e627839dd2dc.png)

I wonder the process of the matching evaluation.
In your **data_dump.py** you compared the **geod_d** with **config.obj_geod_th**(default value is 0.0001) to determine the matching pair quality.

Then the **geod_d** calculation is initially from the parameters from the camera intrinsics and extrinsics data files(those calibration files)  to get **dR** and **dt**

Next you set **config.obj_geod_type == "episym"** by default to calculate the **geod_d** value from **(x1,x2,dR,dt)**.
I still got confused for the (x1,x2) calculation for the complex numpy operations...... 
I guess **x1** is the point coordinates in image ii and the **x2** is the matching point coordinates in image jj with x1.
I am not sure.
 
I wonder: 
1. What is the difference between the **config.obj_geod_type** options? The other 2 are: **sampson** and **episqr**
2. Is there any approach in **config.py** to set the display result save model on?

**Comment by etrulls** [comment]
1 -> "episym" is the symmetric epipolar distance, and "sampson" is the sampson distance. "episqr" is probably the symmetric epipolar distance, squared? To understand what they are, we typically recommend "Multiple View Geometry" (Zisserman & Hartley), but you can use other resources. You shouldn't touch this one. The calculations are not complex, but if you have trouble with the code you should check out the paper (see Eq. 8).
2 -> I'm not sure what you're trying to do. What do you mean by "save model"?

**Comment by ZeroSteven618** [comment]
Thanks for your reply!

For 2: I mean is there any config setting in **config.py** to save the matching pairs(lining with green and red) result images as **imwrite** call in OpenCV

For 1: I would like to re-achieve the matching display result as you did in your paper in my own image data and I got confused for the process especially the numpy operations in generating **(x1,x2)** in the code.  I will check the **Eq.8** in your paper.

In addition, if the data in calibration files from the dataset are transformed from VisualSFM. I wonder the process of transforming the VSFM data into your calibration files.
 
In the nvm file from VSFM, each image will have parameters as:
    **focal length, quaternion WXYZ, camera center, radial distortion, 0**
In your calibration files you have **K,R,T** matrix and **dc**(You mentioned the dc is not used in another issue) value for each image.
Is there any guide to transform the VSFM parameters into your calibration matrix files?

**Comment by ZeroSteven618** [comment]
Excuse me, @etrulls 
I tried to transform the **nvm** camera parameters into your calibration data files with **K,R,T** matrix.

In the nvm file from VSFM, each image will have parameters as:
**focal length, quaternion WXYZ, camera center, radial distortion, 0**

I did the transformation as follows:
The **K** matrix is as: **[focal length,0,0],[0,focal length,0],[0,0,1]**
The **R** matrix is from **quaternion WXYZ** and I noticed the **quaternion_matrix(quaternion)** call in your **transformations.py** so I put the WXYZ quaternion into it for R matrix as **3×3**(Your **original result** is **4×4** numpy array)
The **T** matrix is as the **camera center** in the nvm file. I directly set the 3 elements of camera center as the **T** matrix

Then I did matching pairs evaluation as follows:
I picked 2 images in your **Reichstag** dataset and did **SIFT+BFMatch+distance sorted matching** to pick up the first 100 matches(high quality matches). 
The 2 images are:
![1](https://user-images.githubusercontent.com/66064813/98208264-fb24e300-1f77-11eb-882e-450de659eb5c.jpg)
![2](https://user-images.githubusercontent.com/66064813/98208281-ffe99700-1f77-11eb-82e9-00d942f186fa.jpg)


Then I use your calibration h5 files to do evaluation from **your K,R,T matrix** and the result:
![1 2_100_sift_match](https://user-images.githubusercontent.com/66064813/98208376-23acdd00-1f78-11eb-9eae-aa1ab8096bb1.jpg)
I checked each single match through my eye by displaying them one by one and the green ones are certainly right and the red ones are certainly wrong.  
Your calibration files are quite convincing. 

However I did the matching evaluation with my transformation from **VSFM camera data** to your **K,R,T** matrix but got like this:
![1 2_100_sift_allwrong_match](https://user-images.githubusercontent.com/66064813/98208572-74bcd100-1f78-11eb-9db8-0a2230ff7024.jpg)

All of the matches are regarded as wrong. The 100 matches are the same as the former image.

I do not know how to get the camera data in nvm file from **VSFM** into your calibration **K,R,T** matrix.
My trial is not right but I do not know where the fault is.

Could you please give me more hints? Thanks.

**Comment by etrulls** [comment]
There are two things that come to mind. One is that the camera center might be off, because VSFM convention's is different (hence the zeros in the calibration matrix). You can check the values in our calibration files to check if they're different. The other is that we may be using different conventions (e.g. world-to-cam or cam-to-world).

Honestly I don't quite remember, we deprecated VSFM in favour of COLMAP years ago. Why are you trying to do the conversion yourself? If you want to use your own (new) reconstructions you should look into COLMAP and the format used [here](https://github.com/ubc-vision/image-matching-benchmark). We don't have the bandwidth to support this.

**Comment by ZeroSteven618** [comment]
Well, Thanks for your immediate reply!

> Why are you trying to do the conversion yourself?

I would like to see the matching pairs accuracy by judging them through the ground truth perspective relationship between the 2 images.
The camera matrix are vital for this step. 
But I do not have any camera data with my test images. 
I only have the images **without camera information**.
But I can create the **putative** camera data info for each image by VSFM. 
So I began the curly trial to transform the VSFM camera model into your calibration files with **K,R,T** matrix. 
Then I would like to do the evaluation as I displayed in the former reply.

As for your COLMAP, I will check it.
Thanks.

**Comment by etrulls** [comment]
Move to COLMAP then, it should give you better reconstructions and that's what we support now. It's pretty easy, but you have an example [here](https://github.com/ubc-vision/image-matching-benchmark/blob/master/example/training_data/parse_data.ipynb) if you don't want to start from scratch. There's some preprocessing we do for the benchmark data, but I think this should be able to read raw reconstructions.

Since this is not really about the paper anymore I'll close this ticket.

**Comment by ZeroSteven618** [comment]
Excuse me, @etrulls Sorry to make issues about COLMAP here.

I tried COLMAP with a dataset and got **sparse** folder with putative camera information.
However, the **intrinsics** matrix is in **sparse/camera.bin**. Then **extrinsics** matrix for each image is in **images.bin**

I wonder:
1. How to open the bin files to load the data?
2. How to transform those data into your **K,R,T matrix** as you provided in the **calibration** files in this repo?

**Comment by etrulls** [comment]
Replying on the other thread.

**Comment by ZeroSteven618** [comment]
I posted a new issue in your COLMAP repo
Link:
https://github.com/ubc-vision/image-matching-benchmark/issues/30
