### ISSUE TITLE
a problem from No train, and directly test on your code

### ISSUE THREAD

**Issue by shuchao1212** [vcg-uvic/learned-correspondence-release#4]
Dear Author, thanks for your great work.

here, I just download the test dataset --reichstag and ./dump_data.py --data_tr=reichstag --data_va=reichstag --data_te=reichstag.

then I run  : ./main.py --run_mode=test --res_dir="./" --log_dir="models" --test_log_dir="results" --data_tr="st_peters.brown_bm_3_05" --data_va="reichstag" --data_te="reichstag" .

But there is a problem happened, which troubled me several days, can you give me some guides:

Building Graph
(?, 1, ?, 4)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, 1, ?, 128)
(?, ?)
X shape = (?, ?, 9)
wX shape = (?, ?, 9)
XwX shape = (?, 9, 9)
Loading valid data
Loading test data
Restoring from ./models/models-best...
[st_peters.brown_bm_3_05] Sat Oct 13 21:18:02 2018: Start testing
2018-10-13 21:18:02.774534: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x52a5080
[st_peters.brown_bm_3_05] Sat Oct 13 21:18:14 2018: End testing

What's wrong?

**Comment by kmyid** [comment]
I think it's running properly?
