### ISSUE TITLE
Why choose Resnet instead of raw CNN? 

### ISSUE THREAD

**Issue by punisher220** [vcg-uvic/learned-correspondence-release#42]
Hello, I want to know why you choose Resnet rather than raw CNN.
You set 12 Resnet blocks and there are 26 Perceptron layers in total for your network. Is it right?

Are there any reasons apart from **Degeneration** for networks with high depth?

**Comment by kmyi** [comment]
We tried multiple achitectures, and without residual connections it does not work.
