### ISSUE TITLE
Reichstag data set number of examples

### ISSUE THREAD

**Issue by axelflinth** [vcg-uvic/learned-correspondence-release#50]
Thanks for the awesome work! 

When running the preprocessing step for the reichstag dataset, we obtain 3302 image pairs for training. However, section A.2 ofyour paper states that one can get 'over 1500 examples' when accounting for visibility constraints. There seems to be a discrepancy here, and we are wondering why it is there. Was the vis_threshold maybe tuned for the limited data setting? Or is just 'more than 1500' comparing to the amount of examples for other image pairs used earlier in the paper?

**Comment by etrulls** [comment]
Reichstag has 75 images, of which 59 are used for training. 59 * (59 - 1) / 2 = 1711. Some are dropped with the co-visibility threshold, which would bring it down to the ~1500 mentioned in the paper. You're probably considering pairs {A, B} and {B, A} as separate examples.

**Comment by axelflinth** [comment]
OK, I think that settles the issue, thanks.
