### ISSUE TITLE
About visibility/*.txt

### ISSUE THREAD

**Issue by szgy66** [vcg-uvic/learned-correspondence-release#51]
Hi, thanks for your project. I want to know what dose the file in the visibility mean, for example, vis_000001.txt?

**Comment by etrulls** [comment]
It's the number of co-visible SfM points between the image indicated by the file name and the images listed in the visibility file in the parent folder (or -1 if it's itself). So for instance, on reichstag/val, `vis_000001.txt` contains `-1 918 782 [...]`, so the number of matches between images 1 and 2 is 918. The actual filenames are in `images.txt`.

We used this to filter non-matchable images or very difficult pairs by thresholding to 100 ([example](https://github.com/vcg-uvic/learned-correspondence-release/blob/58ed0fa8aa402b6802ae31721b22bbe7851ea34f/config.py#L219)). For the indoors dataset it was a bit different -- I believe we projected points over a grid using the depth maps and calculated the ratio.

**Comment by szgy66** [comment]
> It's the number of co-visible SfM points between the image indicated by the file name and the images listed in the visibility file in the parent folder (or -1 if it's itself). So for instance, on reichstag/val, `vis_000001.txt` contains `-1 918 782 [...]`, so the number of matches between images 1 and 2 is 918. The actual filenames are in `images.txt`.
> 
> We used this to filter non-matchable images or very difficult pairs by thresholding to 100 ([example](https://github.com/vcg-uvic/learned-correspondence-release/blob/58ed0fa8aa402b6802ae31721b22bbe7851ea34f/config.py#L219)). For the indoors dataset it was a bit different -- I believe we projected points over a grid using the depth maps and calculated the ratio.

thanks for your replying， I get!
